src/Entity/Car.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarRepository")
 */
class Car
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $star;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $fax;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $location;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="cars")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $detail;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="car")
     */
    private $images;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $userid;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getStar(): ?int
    {
        return $this->star;
    }

    public function setStar(?int $star): self
    {
        $this->star = $star;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(?string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setCar($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getCar() === $this) {
                $image->setCar(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return strval($this->id);
        // TODO: Implement __toString() method.
    }

    public function getUserid(): ?int
    {
        return $this->userid;
    }

    public function setUserid(?int $userid): self
    {
        $this->userid = $userid;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Controller/Admin/CarController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Car;
use App\Form\CarType;
use App\Repository\CarRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/car")
 */
class CarController extends AbstractController
{
    /**
     * @Route("/", name="admin_car_index", methods={"GET"})
     */
    public function index(CarRepository $carRepository): Response
    {
        return $this->render('admin/car/index.html.twig', [
            'cars' => $carRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_car_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $car = new Car();
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //dump($car);
            $file = $request->files->get('car')['image'];
            if($file)
            {

                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $newname = uniqid() . $originalFilename .'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('upload_directory'),
                        $newname
                    );
                } catch (FileException $e) {
                    dump("Something went wrong");
                    die();
                }
                $car->setImage($newname);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($car);
                $entityManager->flush();

                return $this->redirectToRoute('admin_car_index');
            }else{
                dump("Couldnt move");
                die();
            }


        }

        return $this->render('admin/car/new.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_car_show", methods={"GET"}, requirements={"id":"\d+"})
     */
    public function show(Car $car): Response
    {
        return $this->render('admin/car/show.html.twig', [
            'car' => $car,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_car_edit", methods={"GET","POST"}, requirements={"id":"\d+"})
     */
    public function edit(Request $request, Car $car): Response
    {
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $request->files->get('car')['image'];
            if($file)
            {

                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $newname = uniqid() . $originalFilename .'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('upload_directory'),
                        $newname
                    );
                } catch (FileException $e) {
                    dump("Something went wrong");
                    die();
                }
                $car->setImage($newname);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($car);
            $entityManager->flush();
            return $this->redirectToRoute('admin_car_index');
        }

        return $this->render('admin/car/edit.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_car_delete", methods={"DELETE"}, requirements={"id":"\d+"})
     */
    public function delete(Request $request, Car $car): Response
    {
        if ($this->isCsrfTokenValid('delete'.$car->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($car);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_car_index');
    }

}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Form\Car1Type;
use App\Form\CarType;
use App\Repository\CarRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user/car")
 */
class CarController extends AbstractController
{
    /**
     * @Route("/", name="user_car_index", methods={"GET"})
     */
    public function index(CarRepository $carRepository): Response
    {
        $user = $this->getUser();//get login User data
        return $this->render('car/index.html.twig', [
            'cars' => $carRepository->findBy(['userid'=>$user->getId()]),
        ]);
    }

    /**
     * @Route("/new", name="user_car_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $car = new Car();
        $form = $this->createForm(Car1Type::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $file = $request->files->get('car1')['image'];
            if($file)
            {

                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $newname = uniqid() . $originalFilename .'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('upload_directory'),
                        $newname
                    );
                } catch (FileException $e) {
                    dump("Something went wrong");
                    die();
                }
                $car->setImage($newname);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($car);
                $entityManager->flush();

            }else{
                dump("Couldnt move");
                die();
            }
            $user = $this->getUser();//get login User data
            $car->setUserid($user->getId());
            $car->setStatus("New");
            $entityManager->persist($car);
            $entityManager->flush();

            return $this->redirectToRoute('user_car_index');
        }

        return $this->render('car/new.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_car_show", methods={"GET"}, requirements={"id":"\d+"})
     */
    public function show(Car $car): Response
    {
        return $this->render('car/show.html.twig', [
            'car' => $car,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_car_edit", methods={"GET","POST"},requirements={"id":"\d+"})
     */
    public function edit(Request $request, Car $car): Response
    {
        $form = $this->createForm(Car1Type::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $request->files->get('car1')['image'];
            if($file)
            {

                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $newname = uniqid() . $originalFilename .'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('upload_directory'),
                        $newname
                    );
                } catch (FileException $e) {
                    dump("Something went wrong");
                    die();
                }
                $car->setImage($newname);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($car);
            $entityManager->flush();


            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_car_index');
        }

        return $this->render('car/edit.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @return string
     */
    private function generateUniqueFileName(){
        //md5() reduces the similarity of the file names generated by
        //uniqid(), which is based on timestamps
        return  md5(uniqid());
    }
    /**
     * @Route("/{id}", name="user_car_delete", methods={"DELETE"}, requirements={"id":"\d+"})
     */
    public function delete(Request $request, Car $car): Response
    {
        if ($this->isCsrfTokenValid('delete'.$car->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($car);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_car_index');
    }
}

templates/car/_delete_form.html.twig
<form method="post" action="{{ path('user_car_delete', {'id': car.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ car.id) }}">
    <button class="btn btn-block btn-danger" style="background: #AA3333">Delete</button>
</form>

templates/car/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/car/edit.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
    <SCRIPT language="JavaScript" type="text/javascript" >
        function openWin( windowURL, windowName, windowFeatures) { window.open(windowURL,windowName,windowFeatures);

        }
    </SCRIPT>
    <div class="responsive-menu">
        <a href="" class="responsive-menu-close"><i class="ion-android-close"></i></a>
        <nav class="responsive-nav"></nav> <!-- end .responsive-nav -->
    </div> <!-- end .responsive-menu -->
    <div class="page-title" style="background-image: url('{{ asset('assets') }}/images/background01.jpg');">
        <div class="inner">
            <div class="container">
                <div class="title">Blog Page</div> <!-- end .title -->
            </div> <!-- end .container -->
        </div> <!-- end .inner -->
    </div> <!-- end .page-title -->

    <section class="section white">
        <div class="inner">
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="blog-list">
                            <div class="blog-post">
                                <h4 class="title"><a href="blog-post.html">User Car List</a></h4>

    {{ include('car/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_car_index') }}">back to list</a>

    {{ include('car/_delete_form.html.twig') }}
    </div> <!-- end .blog-post -->

    </div> <!-- end .blog-list -->

    </div> <!-- end .col-sm-9 -->
    <div class="col-sm-3">
        <div class="sidebar">
            <div class="widget">
                <form class="search-form">
                    <input type="search" placeholder="search" />
                    <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div> <!-- end .widget -->
            <div class="widget">
                {{ include('user/usermenu.html.twig') }}

            </div> <!-- end .widget -->

        </div> <!-- end .sidebar -->
    </div> <!-- end .col-sm-3 -->
    </div>
    </div> <!-- end .container -->
    </div> <!-- end .inner -->
    </section> <!-- end .section -->


{% endblock %}

templates/car/new.html.twig
{% extends 'homebase.html.twig' %}
{% block title %}New Car{% endblock %}

{% block body %}
<SCRIPT language="JavaScript" type="text/javascript" >
    function openWin( windowURL, windowName, windowFeatures) { window.open(windowURL,windowName,windowFeatures);

    }
</SCRIPT>
<div class="responsive-menu">
    <a href="" class="responsive-menu-close"><i class="ion-android-close"></i></a>
    <nav class="responsive-nav"></nav> <!-- end .responsive-nav -->
</div> <!-- end .responsive-menu -->
<div class="page-title" style="background-image: url('{{ asset('assets') }}/images/background01.jpg');">
    <div class="inner">
        <div class="container">
            <div class="title">Blog Page</div> <!-- end .title -->
        </div> <!-- end .container -->
    </div> <!-- end .inner -->
</div> <!-- end .page-title -->

<section class="section white">
    <div class="inner">
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="blog-list">
                        <div class="blog-post">
                            <h4 class="title"><a href="blog-post.html">User Car List</a></h4>

                            {{ include('car/_form.html.twig') }}

                            <a href="{{ path('user_car_index') }}">back to list</a>
                        </div> <!-- end .blog-post -->

                    </div> <!-- end .blog-list -->

                </div> <!-- end .col-sm-9 -->
                <div class="col-sm-3">
                    <div class="sidebar">
                        <div class="widget">
                            <form class="search-form">
                                <input type="search" placeholder="search" />
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div> <!-- end .widget -->
                        <div class="widget">
                            {{ include('user/usermenu.html.twig') }}

                        </div> <!-- end .widget -->

                    </div> <!-- end .sidebar -->
                </div> <!-- end .col-sm-3 -->
            </div>
        </div> <!-- end .container -->
    </div> <!-- end .inner -->
</section> <!-- end .section -->


{% endblock %}

templates/car/show.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
    <div class="responsive-menu">
        <a href="" class="responsive-menu-close"><i class="ion-android-close"></i></a>
        <nav class="responsive-nav"></nav> <!-- end .responsive-nav -->
    </div> <!-- end .responsive-menu -->
    <div class="page-title" style="background-image: url('{{ asset('assets') }}/images/background01.jpg');">
        <div class="inner">
            <div class="container">
                <div class="title">Blog Page</div> <!-- end .title -->
            </div> <!-- end .container -->
        </div> <!-- end .inner -->
    </div> <!-- end .page-title -->

    <section class="section white">
        <div class="inner">
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="blog-list">
                            <div class="blog-post">

                                <h1>User Profile Information</h1>
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <th>Id</th>
                                        <td>{{ car.id }}</td>
                                    </tr>
                                    <tr>
                                        <th>Title</th>
                                        <td>{{ car.title }}</td>
                                    </tr>
                                    <tr>
                                        <th>Keywords</th>
                                        <td>{{ car.keywords }}</td>
                                    </tr>
                                    <tr>
                                        <th>Description</th>
                                        <td>{{ car.description }}</td>
                                    </tr>
                                    <tr>
                                        <th>Image</th>
                                        <td>{{ car.image }}</td>
                                    </tr>
                                    <tr>
                                        <th>Price</th>
                                        <td>{{ car.price }}</td>
                                    </tr>
                                    <tr>
                                        <th>Address</th>
                                        <td>{{ car.address }}</td>
                                    </tr>
                                    <tr>
                                        <th>Phone</th>
                                        <td>{{ car.phone }}</td>
                                    </tr>
                                    <tr>
                                        <th>Fax</th>
                                        <td>{{ car.fax }}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td>{{ car.email }}</td>
                                    </tr>
                                    <tr>
                                        <th>City</th>
                                        <td>{{ car.city }}</td>
                                    </tr>
                                    <tr>
                                        <th>Country</th>
                                        <td>{{ car.country }}</td>
                                    </tr>
                                    <tr>
                                        <th>Location</th>
                                        <td>{{ car.location }}</td>
                                    </tr>
                                    <tr>
                                        <th>Status</th>
                                        <td>{{ car.status }}</td>
                                    </tr>
                                    <tr>
                                        <th>Created_at</th>
                                        <td>{{ car.createdAt ? car.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                                    </tr>
                                    <tr>
                                        <th>Updated_at</th>
                                        <td>{{ car.updatedAt ? car.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                                    </tr>
                                    <tr>
                                        <th>Detail</th>
                                        <td>{{ car.detail }}</td>
                                    </tr>
                                    <tr>
                                        <th>Userid</th>
                                        <td>{{ car.userid }}</td>
                                    </tr>
                                    </tbody>
                                </table>

                                <a href="{{ path('user_car_index') }}" >Back to list</a>
                                <br>
                                <a href="{{ path('user_car_edit', {'id': car.id}) }}" >Edit</a>
                                <br>
                                <a href="{{ path('user_edit', {'id': app.user.id}) }}">Edit Profile</a>
                                {{ include('car/_delete_form.html.twig') }}



                            </div> <!-- end .blog-post -->

                        </div> <!-- end .blog-list -->

                    </div> <!-- end .col-sm-9 -->
                    <div class="col-sm-3">
                        <div class="sidebar">
                            <div class="widget">
                                <form class="search-form">
                                    <input type="search" placeholder="search" />
                                    <button type="submit"><i class="fa fa-search"></i></button>
                                </form>
                            </div> <!-- end .widget -->
                            <div class="widget">
                                {{ include('user/usermenu.html.twig') }}

                            </div> <!-- end .widget -->

                        </div> <!-- end .sidebar -->
                    </div> <!-- end .col-sm-3 -->
                </div>
            </div> <!-- end .container -->
        </div> <!-- end .inner -->
    </section> <!-- end .section -->




{% endblock %}